rebirth:
  points-per-rebirth: 1
  auto-open-skill-tree: true
  base_cost: 1000000        # Cost for first rebirth
  cost_growth: 1.15         # Exponential growth factor
  requirements:
    - type: "rank"
      enabled: true
      value: 26 # rank ID, not prefix
    - type: "prestige"
      enabled: true
      value: 5 # prestige ID, not prefix
    - type: "cost"
      enabled: true
