name: BetterRebirth
version: '1.0.2'
main: dev.phoenixxo.BetterRebirth
api-version: '1.20'
load: STARTUP
authors: [ Phoenixxo ]
description: An better rebirth plugin for XPrison.
depend: [ X-Prison, PlaceholderAPI ]
commands:
  rebirth:
    description: Root command for Better Rebirth plugin.
    usage: /rebirth <gui|reload|level>
    permission: better-rebirth.command
permissions:
  better-rebirth.command:
    default: true
  better-rebirth.ascend:
    default: true
  better-rebirth.reload:
    default: op
  better-rebirth.setlevel:
    default: op

